
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team01-m23-10am-2
owner: ucsb-cs156-m23
repo_name: team01-m23-10am-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NzExNDA2","is_bot":false,"login":"kirrarista","name":"Kirill Aristarkhov"},"headRefName":"Kirill-ZipCodeQuery","number":17,"title":"Add ZipCode Service and Tests","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-2/pull/17"},{"author":{"id":"U_kgDOBh3zbg","is_bot":false,"login":"jczhou02","name":"Joshua Zhou"},"headRefName":"Josh-PublicHoliday","number":16,"title":"Add PublicHoliday Service and Controller","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-2/pull/16"},{"author":{"id":"MDQ6VXNlcjc3NzEwNjU5","is_bot":false,"login":"cyrus895","name":""},"headRefName":"Cyrus-UniversityQuery","number":15,"title":"Add UniversityQueryService and Controller","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-2/pull/15"}]
